spring.application.name=solutions2
server.port=8082

spring.datasource.url=jdbc:postgresql://db.feinvzouqgzmqyvizodo.supabase.co:5432/postgres?user=&password=[YOUR-PASSWORD]
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=meeting_schema

spring.kafka.producer.bootstrap-servers=kafka:9092
spring.kafka.producer.topic.name=registration-events

PUBLIC_KEY_PATH=/app/secrets/public_key.pem